use std::{env, fs, path::PathBuf};

fn main() {
    generate_device_registry();

    let mut res = winres::WindowsResource::new();
    res.set_icon("assets/ShellyRGBAudio.ico");
    res.set("FileDescription", "ShellyRGBAudio");
    res.set("ProductName", "ShellyRGBAudio");
    res.set("CompanyName", "SytxLabs");
    res.set("LegalCopyright", "© 2026 SytxLabs");
    res.set("OriginalFilename", "ShellyRGBAudio.exe");
    res.compile().unwrap();
}

/// Scans `src/devices/*.rs` and writes the module declarations plus the device registry into `$OUT_DIR/device_registry.rs`, which `src/devices/mod.rs`
/// includes. Dropping a new `*.rs` file into `src/devices/` is therefore enough to register a device; the file only has to expose
/// `pub const DESCRIPTOR: DeviceDescriptor`.
fn generate_device_registry() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let devices_dir = manifest_dir.join("src").join("devices");

    println!("cargo:rerun-if-changed={}", devices_dir.display());

    let mut modules: Vec<(String, String)> = Vec::new();
    for entry in fs::read_dir(&devices_dir).expect("read src/devices") {
        let path = entry.expect("read src/devices entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("device file name is not valid utf-8")
            .to_string();
        if stem == "mod" {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        // Forward slashes work in `#[path]` on every platform and need no escaping.
        modules.push((stem, path.to_string_lossy().replace('\\', "/")));
    }
    modules.sort();

    let mut out = String::from("// @generated by build.rs - do not edit.\n\n");
    for (name, path) in &modules {
        out.push_str(&format!("#[path = \"{path}\"]\npub mod {name};\n"));
    }
    out.push_str("\n/// Every device discovered in `src/devices/`.\npub static REGISTRY: &[DeviceDescriptor] = &[\n");
    for (name, _) in &modules {
        out.push_str(&format!("    {name}::DESCRIPTOR,\n"));
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("device_registry.rs");
    fs::write(&out_path, out).expect("write device_registry.rs");
}
