// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioSection } from "./AudioSection";
import type { BandConfig } from "./BandConfig";
import type { ColorMapConfig } from "./ColorMapConfig";
import type { DynamicsSection } from "./DynamicsSection";
import type { OutputSection } from "./OutputSection";
import type { SpatialSection } from "./SpatialSection";
import type { JsonValue } from "./serde_json/JsonValue";

export type AppConfig = { audio: AudioSection, bands: Array<BandConfig>, color_map: ColorMapConfig, dynamics: DynamicsSection, output: OutputSection, spatial: SpatialSection, devices: Array<JsonValue>, };
