// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppGroup = { name: string, enabled: boolean, apps: Array<string>, gain: number, };
