// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppGroup } from "./AppGroup";
import type { AppMatchMode } from "./AppMatchMode";

export type AppsSection = { enabled: boolean, mode: AppMatchMode, include_process_tree: boolean, rescan_ms: number, sample_rate: number | null, channels: number | null, groups: Array<AppGroup>, };
