// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppsSection } from "./AppsSection";
import type { AudioDeviceSelector } from "./AudioDeviceSelector";
import type { Downmix } from "./Downmix";
import type { WindowKind } from "./WindowKind";

export type AudioSection = { device: AudioDeviceSelector, apps: AppsSection, fft_size: number, hop_size: number, window: WindowKind, downmix: Downmix, buffer_duration_hns: number, silence_timeout_ms: number, silence_fade_ms: number, silence_brightness: number, };
