// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioDeviceInfo = { id: string, name: string, layout: string | null, is_default: boolean, is_loopback: boolean, };
