// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BandConfig = { name: string, from_hz: number, to_hz: number, weight: number, color: string | null, };
