// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorStop } from "./ColorStop";
import type { Interpolation } from "./Interpolation";
import type { Scale } from "./Scale";
import type { WhiteChannel } from "./WhiteChannel";

export type ColorMapConfig = { stops: Array<ColorStop>, frequency_scale: Scale, interpolation: Interpolation, saturation: number, value_floor: number, value_span: number, white_channel: WhiteChannel, white_fixed: number, fallback_color: string, };
