// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceForm } from "./DeviceForm";

export type DeviceSpatialConfig = { form: DeviceForm, position: [number, number, number] | null, extent: [number, number, number], path: [number, number, number][] | null, spatiality: number, elevation_tilt: number | null, focus: number | null, distance_falloff: number | null, };
