// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LevelSource } from "./LevelSource";
import type { Normalize } from "./Normalize";

export type DynamicsSection = { normalize: Normalize, level_source: LevelSource, log_offset: number, peak_floor: number, peak_decay: number, level_alpha: number, band_attack: number, band_release: number, flux_alpha: number, beat_threshold: number, beat_cooldown_ms: number, strobe_ms: number, strobe_level: number, strobe_color: string | null, };
