// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineState } from "./EngineState";
import type { SpeakerPlacement } from "./SpeakerPlacement";

export type EngineStatus = { state: EngineState, source: string | null, sample_rate: number | null, channels: number | null, layout: string | null, speakers: Array<SpeakerPlacement>, devices: Array<string>, warnings: Array<string>, error: string | null, };
