// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeakerRole } from "./SpeakerRole";

/**
 * Which speaker sits on which capture channel.
 */
export type LayoutSelector = "auto" | { "channels": Array<SpeakerRole> };
