// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the brightness level comes from.
 */
export type LevelSource = "peak" | "average";
