// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputSection = { change_interval_ms: number, transition_min_ms: number, transition_max_ms: number, transition_beat_weight: number, transition_level_weight: number, transition_curve: number, deadband_rgb: number, deadband_overall: number, brightness_floor: number, gamma_min: number, gamma_max: number, };
