// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `#[serde(default)]` so stating only one corner keeps the other at its default rather than making the whole config unreadable.
 */
export type RoomBounds = { min: [number, number, number], max: [number, number, number], };
