// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutSelector } from "./LayoutSelector";
import type { RoomBounds } from "./RoomBounds";

export type SpatialSection = { enabled: boolean, layout: LayoutSelector, room: RoomBounds, focus: number, omni_floor: number, strip_samples: number, height_sharpness: number, distance_falloff: number, };
