// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeakerRole = "front_left" | "front_right" | "front_center" | "lfe" | "back_left" | "back_right" | "front_left_of_center" | "front_right_of_center" | "back_center" | "side_left" | "side_right" | "top_center" | "top_front_left" | "top_front_center" | "top_front_right" | "top_back_left" | "top_back_center" | "top_back_right" | "unknown";
