// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeakerRole } from "./SpeakerRole";

export type SpeakerPlacement = { channel: number, role: SpeakerRole, short_name: string, direction: [number, number, number], };
